/* Generated By:JavaCC: Do not edit this line. LambdaCalculusParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LambdaCalculusParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VARIABLE = 13;
  /** RegularExpression Id. */
  int EXPONENT = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int STRING = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\"lambda\"",
    "\".\"",
    "\")\"",
    "\"define\"",
    "\"load\"",
    "\"if\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<token of kind 12>",
    "<VARIABLE>",
    "<EXPONENT>",
    "<NUMBER>",
    "<STRING>",
  };

}
